[package]

name = "qmlrs"
version = "0.0.1"
authors = ["Mikko Perttunen <cyndis@kapsi.fi>"]
license = "MIT/Apache-2.0"

build = "build.rs"

[dependencies]
libc = "^0.2.6"

[build-dependencies]
pkg-config = "^0.3.6"
